{
 "title": "SOA-Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Follower logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fluent-bit\", container_name=\"/followers_server\"}"
    }
   ]
  },
  {
   "title": "Blog logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fluent-bit\", container_name=\"/blog_server\"}"
    }
   ]
  },
  {
   "title": "Tours logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fluent-bit\", container_name=\"/tours_server\"}"
    }
   ]
  },
  {
   "title": "Stakeholders log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fluent-bit\", container_name=\"/stakeholder_server\"}"
    }
   ]
  },
  {
   "title": "Count logs for whole backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"fluent-bit\"}[5m])\r\n"
    }
   ]
  }
 ]
}