version: "3.7"

services:
  stakeholders:
    build:
      context: ./stakeholders
      dockerfile: Dockerfile
    image: stakeholder_web_server
    container_name: stakeholder_server
    restart: on-failure
    networks:
      - servers
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    
  
  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    image: blog_web_server
    container_name: blog_server
    restart: on-failure
    networks:
      - servers
    ports:
      - 8081:8081
    depends_on:
      database:
        condition: service_healthy

  tours:
    build:
      context: ./tours
      dockerfile: Dockerfile
    image: tours_web_server
    container_name: tours_server
    restart: on-failure
    networks:
      - servers
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017/soadb?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy

  followers:
    build:
      context: ./followers
      dockerfile: Dockerfile
    image: followers_web_server
    container_name: followers_server
    restart: always
    networks:
      - servers
    ports:
      - 8084:8084
    environment:
      - PORT=8084
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pass
    depends_on:
      neo4j:
        condition: service_healthy


  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - servers
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soadb
      MYSQL_ROOT_HOST: '%'
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    command: --default-authentication-plugin=mysql_native_password

  # NoSQL: MongoDB
  mongo:
    image: mongo
    restart: always
    networks:
      - servers
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: soadb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  # NoSQL: Mongo Express (GUI)
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - servers
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8083:8081"
    volumes:
      - mongo_express_data:/data/db
# NoSql Neo4j baza

  neo4j:
    image: neo4j:5.23
    container_name: neo4j
    restart: always
    networks:
      - servers
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"   
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p pass || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/pass   # username: neo4j, password: pass
    volumes:
      - neo4j_data:/data


volumes:
  database-data:
    name: server-database
  mongo_store:
  mongo_express_data:
  neo4j_data:

networks:
  servers:
    name: servers
    driver: bridge
