/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: shopping.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as shopping_pb from './shopping_pb'; // proto import: "shopping.proto"


export class ShoppingCartServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddToCart = new grpcWeb.MethodDescriptor(
    '/proto.ShoppingCartService/AddToCart',
    grpcWeb.MethodType.UNARY,
    shopping_pb.AddToCartRequest,
    shopping_pb.ShoppingCartResponse,
    (request: shopping_pb.AddToCartRequest) => {
      return request.serializeBinary();
    },
    shopping_pb.ShoppingCartResponse.deserializeBinary
  );

  addToCart(
    request: shopping_pb.AddToCartRequest,
    metadata?: grpcWeb.Metadata | null): Promise<shopping_pb.ShoppingCartResponse>;

  addToCart(
    request: shopping_pb.AddToCartRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: shopping_pb.ShoppingCartResponse) => void): grpcWeb.ClientReadableStream<shopping_pb.ShoppingCartResponse>;

  addToCart(
    request: shopping_pb.AddToCartRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: shopping_pb.ShoppingCartResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.ShoppingCartService/AddToCart',
        request,
        metadata || {},
        this.methodDescriptorAddToCart,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.ShoppingCartService/AddToCart',
    request,
    metadata || {},
    this.methodDescriptorAddToCart);
  }

  methodDescriptorCheckout = new grpcWeb.MethodDescriptor(
    '/proto.ShoppingCartService/Checkout',
    grpcWeb.MethodType.UNARY,
    shopping_pb.CheckoutRequest,
    shopping_pb.CheckoutResponse,
    (request: shopping_pb.CheckoutRequest) => {
      return request.serializeBinary();
    },
    shopping_pb.CheckoutResponse.deserializeBinary
  );

  checkout(
    request: shopping_pb.CheckoutRequest,
    metadata?: grpcWeb.Metadata | null): Promise<shopping_pb.CheckoutResponse>;

  checkout(
    request: shopping_pb.CheckoutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: shopping_pb.CheckoutResponse) => void): grpcWeb.ClientReadableStream<shopping_pb.CheckoutResponse>;

  checkout(
    request: shopping_pb.CheckoutRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: shopping_pb.CheckoutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.ShoppingCartService/Checkout',
        request,
        metadata || {},
        this.methodDescriptorCheckout,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.ShoppingCartService/Checkout',
    request,
    metadata || {},
    this.methodDescriptorCheckout);
  }

}

